const VIDEO_DATA = [
    {channel: '全明星運動會',
     channel_id: 'UCXxAXdFh-cuYXU289kd-pNQ',
     channel_avatar: 'https://yt3.ggpht.com/ytc/AAUvwng9GJZCxSOlAONujyyQj_jZs_PqW0lKIrPnG1sH=s48-c-k-c0x00ffffff-no-rj',
     description: ['【空氣手槍】、【男子三對三籃球】、【女子射箭】\n',
                    '這根本就是職業水準的比賽啊～\n',
                    '#全明星運動會 #第二季 #頻道會員募集中\n',
                    '加入頻道會員👉https://rb.gy/tzx4nk\n',
                    '大來賓：何守正\n',
                    '主播：徐展元、蔡尚樺\n',
                    '🔴紅隊領隊：江宏傑          🔵藍隊領隊：錢薇娟\n',
                    '🔴紅隊經理：粿粿              🔵藍隊經理：孟潔\n',
                    '🔴紅隊助理教練：喬巴      🔵藍隊助理教練：Choco\n',
                    '🔴紅隊陣容：曹佑寧、王家梁、何孟遠、周予天、小杰 廖允杰、范逸臣、晏柔中、房子 房思瑜、席惟倫、吳心緹\n',
                    '🔵藍隊陣容：林敬倫、潘君侖、顏佑庭、彭小刀、鼓鼓 呂思緯、小春、采子、小8 趙逸嵐、洗菜、李佳薇\n',
                    '\n',
                    '🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆\n',
                    '不搞笑！不做效果！全程玩真的！\n',
                    '全明星運動會，正式開戰！\n',
                    '每週二，中午12點，上架完整版！\n',
                    '\n',
                    '⚠️還沒訂閱嗎？傳送門在這👉https://rb.gy/7uxlh5\n',
                    '👉全明星運動會FaceBook：https://rb.gy/c26gcu\n',
                    '👉全明星運動會Instagram：https://rb.gy/u82tvj'],
    id: '2Qo9jNZ0xe0',
    img_thumbnail: 'https://i.ytimg.com/vi/2Qo9jNZ0xe0/hqdefault.jpg',
    labels: ['全明星運動會', '胡宇威', '李玖哲', '柯有倫', '姚元浩', '陳漢典', '運動實境節目', '台視', '三立'],
    link: 'https://www.youtube.com/watch?v=2Qo9jNZ0xe0',
    thumbnail: 'https://i.ytimg.com/vi_webp/2Qo9jNZ0xe0/maxresdefault.webp?v=6074477e',
    title: ['【這集超帥！】心臟訓練好了嗎？坐穩了，刺激比賽準備開始！不到最後一刻，你永遠不知道誰是贏家，但只要我站在場上，沒人能從我手中搶走勝利！｜全明星運動會S2 ',
            'EP07：女力爆發｜台塑石油95+'],
    upload_date: '20210412',
    view_count: 1237416},
    {channel: '全明星運動會全明星運動會全明星運動會',
     channel_id: 'UCXxAXdFh-cuYXU289kd-pNQ',
     channel_avatar: 'https://yt3.ggpht.com/ytc/AAUvwng9GJZCxSOlAONujyyQj_jZs_PqW0lKIrPnG1sH=s48-c-k-c0x00ffffff-no-rj',
     description: ['【五人制棒球】、【標槍】、【排球交流賽 - 紅藍聯隊 vs 鯨華女排】\n',
                    '就算失誤了，我們還有隊友這個強大的後盾！不要怕～\n',
                    '加入頻道會員👉https://www.youtube.com/channel/UCXxAXdFh-cuYXU289kd-pNQ/join\n',
                    '#全明星運動會 #第二季 #我要破紀錄\n',
                    '大來賓：鄭兆村\n',
                    '主播：徐展元、蔡尚樺\n',
                    '🔴紅隊領隊：江宏傑          🔵藍隊領隊：錢薇娟\n',
                    '🔴紅隊經理：粿粿              🔵藍隊經理：孟潔\n',
                    '🔴紅隊助理教練：喬巴      🔵藍隊助理教練：Choco\n',
                    '🔴紅隊陣容：曹佑寧、王家梁、何孟遠、周予天、小杰 廖允杰、范逸臣、晏柔中、房子 房思瑜、席惟倫、吳心緹\n',
                    '🔵藍隊陣容：林敬倫、潘君侖、顏佑庭、彭小刀、鼓鼓 呂思緯、小春、采子、小8 趙逸嵐、洗菜、李佳薇\n',
                    '\n',
                    '🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆\n',
                    '不搞笑！不做效果！全程玩真的！\n',
                    '全明星運動會，正式開戰！\n',
                    '每週二，中午12點，上架完整版！\n',
                    '\n',
                    '⚠️還沒訂閱嗎？傳送門在這👉https://rb.gy/7uxlh5\n',
                    '👉全明星運動會FaceBook：https://rb.gy/c26gcu\n',
                    '👉全明星運動會Instagram：https://rb.gy/u82tvj'],
    id: 'VQ2pZxGg5v0',
    img_thumbnail: 'https://i.ytimg.com/vi/VQ2pZxGg5v0/hqdefault.jpg',
    labels: ['全明星運動會', '胡宇威', '李玖哲', '柯有倫', '姚元浩', '陳漢典', '運動實境節目', '台視', '三立'],
    link: 'https://www.youtube.com/watch?v=VQ2pZxGg5v0',
    thumbnail: 'https://i.ytimg.com/vi/VQ2pZxGg5v0/maxresdefault.jpg?v=606bc6d0',
    title: ['【破大會紀錄？】就算逆境，也要逆風飛翔，唯有自己，能戰勝自己！那裡，就是記錄的所在，今天，我要超越他！紅藍聯手，對抗外敵！不用多說，派出最強的來！｜全明星運動會S2 ',
            'EP06：突破極限｜台塑石油95+'],
    upload_date: '20210405',
    view_count: 1286698},
    {channel: '全明星運動會',
     channel_id: 'UCXxAXdFh-cuYXU289kd-pNQ',
     channel_avatar: 'https://yt3.ggpht.com/ytc/AAUvwng9GJZCxSOlAONujyyQj_jZs_PqW0lKIrPnG1sH=s48-c-k-c0x00ffffff-no-rj',
     description: ['【游泳接力】、【足球PK賽】、【躲避球】\n',
                    '沒看到最後真的不知道誰輸誰贏啊，太緊張太刺激，心臟負荷不了啦～\n',
                    '加入頻道會員👉https://www.youtube.com/channel/UCXxAXdFh-cuYXU289kd-pNQ/join\n',
                    '#全明星運動會 #第二季 #衝吧運動魂\n',
                    '大來賓：朱木炎\n',
                    '主播：徐展元、蔡尚樺\n',
                    '🔴紅隊領隊：江宏傑          🔵藍隊領隊：錢薇娟\n',
                    '🔴紅隊經理：粿粿              🔵藍隊經理：孟潔\n',
                    '🔴紅隊助理教練：喬巴      🔵藍隊助理教練：Choco\n',
                    '🔴紅隊陣容：曹佑寧、王家梁、何孟遠、周予天、小杰 廖允杰、范逸臣、晏柔中、房子 房思瑜、席惟倫、吳心緹\n',
                    '🔵藍隊陣容：林敬倫、潘君侖、顏佑庭、彭小刀、鼓鼓 呂思緯、小春、采子、小8 趙逸嵐、洗菜、李佳薇\n',
                    '\n',
                    '🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆\n',
                    '不搞笑！不做效果！全程玩真的！\n',
                    '全明星運動會，正式開戰！\n',
                    '每週二，中午12點，上架完整版！\n',
                    '\n',
                    '⚠️還沒訂閱嗎？傳送門在這👉https://rb.gy/7uxlh5\n',
                    '👉全明星運動會FaceBook：https://rb.gy/c26gcu\n',
                    '👉全明星運動會Instagram：https://rb.gy/u82tvj'],
    id: 'WaKMyx9vAXA',
    img_thumbnail: 'https://i.ytimg.com/vi/WaKMyx9vAXA/hqdefault.jpg',
    labels: ['全明星運動會', '胡宇威', '李玖哲', '柯有倫', '姚元浩', '陳漢典', '運動實境節目', '台視', '三立'],
    link: 'https://www.youtube.com/watch?v=WaKMyx9vAXA',
    thumbnail: 'https://i.ytimg.com/vi_webp/WaKMyx9vAXA/maxresdefault.webp?v=6061d6e0',
    title: ['【逆轉再逆轉！】一秒、一球、一個人，就差這麼一點點！技巧的展現，戰術的運用，球是圓的，誰知道最後誰輸誰贏？永不放棄，正面對決到最後一刻！｜全明星運動會S2 ',
            'EP05：正面對決｜台塑石油95+'],
    upload_date: '20210329',
    view_count: 1155015},
    {channel: '全明星運動會',
     channel_id: 'UCXxAXdFh-cuYXU289kd-pNQ',
     channel_avatar: 'https://yt3.ggpht.com/ytc/AAUvwng9GJZCxSOlAONujyyQj_jZs_PqW0lKIrPnG1sH=s48-c-k-c0x00ffffff-no-rj',
     description: ['【保齡球】、【籃球技術挑戰賽】、【健球】\n',
                    '就是因為有強大的對手，我們才能繼續成長！\n',
                    '加入頻道會員👉https://www.youtube.com/channel/UCXxAXdFh-cuYXU289kd-pNQ/join\n',
                    '#全明星運動會 #第二季 #隊長出爐\n',
                    '大來賓：陽建福\n',
                    '主播：徐展元、蔡尚樺\n',
                    '🔴紅隊領隊：江宏傑          🔵藍隊領隊：錢薇娟\n',
                    '🔴紅隊經理：粿粿              🔵藍隊經理：孟潔\n',
                    '🔴紅隊助理教練：喬巴      🔵藍隊助理教練：Choco\n',
                    '🔴紅隊陣容：曹佑寧、王家梁、何孟遠、周予天、小杰 廖允杰、范逸臣、晏柔中、房子 房思瑜、席惟倫、吳心緹\n',
                    '🔵藍隊陣容：林敬倫、潘君侖、顏佑庭、彭小刀、鼓鼓 呂思緯、小春、采子、小8 趙逸嵐、洗菜、李佳薇\n',
                    '\n',
                    '🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆\n',
                    '不搞笑！不做效果！全程玩真的！\n',
                    '全明星運動會，正式開戰！\n',
                    '每週二，中午12點，上架完整版！\n',
                    '\n',
                    '⚠️還沒訂閱嗎？傳送門在這👉https://rb.gy/7uxlh5\n',
                    '👉全明星運動會FaceBook：https://rb.gy/c26gcu\n',
                    '👉全明星運動會Instagram：https://rb.gy/u82tvj'],
    id: 'Z4LJCC37JaQ',
    img_thumbnail: 'https://i.ytimg.com/vi/Z4LJCC37JaQ/hqdefault.jpg',
    labels: ['全明星運動會', '胡宇威', '李玖哲', '柯有倫', '姚元浩', '陳漢典', '運動實境節目', '台視', '三立'],
    link: 'https://www.youtube.com/watch?v=Z4LJCC37JaQ',
    thumbnail: 'https://i.ytimg.com/vi_webp/Z4LJCC37JaQ/maxresdefault.webp?v=6058c944',
    title: ['【誰是隊長？】壓力，前所未有！誰能頂住？隊長，捨我其誰！誰能擔任？全新項目！籃球技術挑戰賽～我要把大家對我的期待，全部發揮出來！｜全明星運動會S2 ',
            'EP04：怪物隊長｜台塑石油95+'],
    upload_date: '20210322',
    view_count: 1378467},
    {channel: '全明星運動會',
     channel_id: 'UCXxAXdFh-cuYXU289kd-pNQ',
     channel_avatar: 'https://yt3.ggpht.com/ytc/AAUvwng9GJZCxSOlAONujyyQj_jZs_PqW0lKIrPnG1sH=s48-c-k-c0x00ffffff-no-rj',
     description: ['【足壘球】、【男子羽球雙打】、【拔河】\n',
                    '第一場比賽就好刺激啊～\n',
                    '加入頻道會員👉https://www.youtube.com/channel/UCXxAXdFh-cuYXU289kd-pNQ/join\n',
                    '#全明星運動會 #誰是MVP #第一次對決\n',
                    '大來賓：謝長亨\n',
                    '主播：徐展元、蔡尚樺\n',
                    '🔴紅隊領隊：江宏傑          🔵藍隊領隊：錢薇娟\n',
                    '🔴紅隊經理：粿粿              🔵藍隊經理：孟潔\n',
                    '🔴紅隊助理教練：喬巴      🔵藍隊助理教練：Choco\n',
                    '🔴紅隊陣容：曹佑寧、王家梁、何孟遠、周予天、小杰 廖允杰、范逸臣、晏柔中、房子 房思瑜、席惟倫、吳心緹\n',
                    '🔵藍隊陣容：林敬倫、潘君侖、顏佑庭、彭小刀、鼓鼓 呂思緯、小春、采子、小8 趙逸嵐、洗菜、李佳薇\n',
                    '\n',
                    '🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆\n',
                    '不搞笑！不做效果！全程玩真的！\n',
                    '全明星運動會，正式開戰！\n',
                    '每週二，中午12點，上架完整版！\n',
                    '\n',
                    '⚠️還沒訂閱嗎？傳送門在這👉https://rb.gy/7uxlh5\n',
                    '👉全明星運動會FaceBook：https://rb.gy/c26gcu\n',
                    '👉全明星運動會Instagram：https://rb.gy/u82tvj'],
    id: '-8b4IVZs5oU',
    img_thumbnail: 'https://i.ytimg.com/vi/-8b4IVZs5oU/hqdefault.jpg',
    labels: ['全明星運動會', '胡宇威', '李玖哲', '柯有倫', '姚元浩', '陳漢典', '運動實境節目', '台視', '三立'],
    link: 'https://www.youtube.com/watch?v=-8b4IVZs5oU',
    thumbnail: 'https://i.ytimg.com/vi_webp/-8b4IVZs5oU/maxresdefault.webp?v=60501dd7',
    title: ['【強強對決！】第一場勝利，第一座MVP，誓言拿下，永不放棄！強與強的碰撞，這就是屬於我們的第二季！｜全明星運動會S2 ',
            'EP03：首戰開打｜台塑石油95+'],
    upload_date: '20210315',
    view_count: 1417812},
    {channel: '全明星運動會',
     channel_id: 'UCXxAXdFh-cuYXU289kd-pNQ',
     channel_avatar: 'https://yt3.ggpht.com/ytc/AAUvwng9GJZCxSOlAONujyyQj_jZs_PqW0lKIrPnG1sH=s48-c-k-c0x00ffffff-no-rj',
     description: ['【跳遠】、【游泳】、【躲避球】\n',
                    '第二季！你想挺哪一隊？\n',
                    '加入頻道會員👉https://www.youtube.com/channel/UCXxAXdFh-cuYXU289kd-pNQ/join\n',
                    '#全明星運動會 #分隊確認 #新隊呼\n',
                    '主播：徐展元、蔡尚樺\n',
                    '🔴紅隊領隊：江宏傑          🔵藍隊領隊：錢薇娟\n',
                    '🔴紅隊經理：粿粿              🔵藍隊經理：孟潔\n',
                    '🔴紅隊助理教練：喬巴      🔵藍隊助理教練：Choco\n',
                    '趙逸嵐、洗菜、房思瑜、吳心緹、席惟倫、李佳薇、晏柔中、采子、王家梁、小春、小杰、曹佑寧、周予天、何孟遠、彭小刀、林敬倫、鼓鼓、潘君侖、范逸臣、顏佑庭\n',
                    '\n',
                    '🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆\n',
                    '不搞笑！不做效果！全程玩真的！\n',
                    '全明星運動會，正式開戰！\n',
                    '每週二，中午12點，上架完整版！\n',
                    '\n',
                    '⚠️還沒訂閱嗎？傳送門在這👉https://rb.gy/7uxlh5\n',
                    '👉全明星運動會FaceBook：https://rb.gy/c26gcu\n',
                    '👉全明星運動會Instagram：https://rb.gy/u82tvj'],
    id: 'sjP8TLu-1Ps',
    img_thumbnail: 'https://i.ytimg.com/vi/sjP8TLu-1Ps/hqdefault.jpg',
    labels: ['全明星運動會', '胡宇威', '李玖哲', '柯有倫', '姚元浩', '陳漢典', '運動實境節目', '台視', '三立'],
    link: 'https://www.youtube.com/watch?v=sjP8TLu-1Ps',
    thumbnail: 'https://i.ytimg.com/vi_webp/sjP8TLu-1Ps/maxresdefault.webp?v=60461b4c',
    title: ['【誰是狀元？】紅藍兩隊正式成軍！新隊呼出爐～誰是狀元？誰是黑馬？錢姊、小傑搶人囉～他和她，都是我的！｜全明星運動會S2 ',
            'EP02：搶人大戰｜台塑石油95+'],
    upload_date: '20210308',
    view_count: 1576945},
    {channel: '全明星運動會',
     channel_id: 'UCXxAXdFh-cuYXU289kd-pNQ',
     channel_avatar: 'https://yt3.ggpht.com/ytc/AAUvwng9GJZCxSOlAONujyyQj_jZs_PqW0lKIrPnG1sH=s48-c-k-c0x00ffffff-no-rj',
     description: ['#全明星運動會 #第二季 #頻道會員募集中\n',
                    '加入頻道會員👉 https://rb.gy/tzx4nk\n',
                    '主播：徐展元、蔡尚樺\n',
                    '🔴紅隊領隊：江宏傑          🔵藍隊領隊：錢薇娟\n',
                    '🔴紅隊經理：粿粿              🔵藍隊經理：孟潔\n',
                    '🔴紅隊助理教練：喬巴      🔵藍隊助理教練：Choco\n',
                    '🔴紅隊陣容：曹佑寧、王家梁、何孟遠、周予天、小杰 廖允杰、范逸臣、晏柔中、房子 房思瑜、席惟倫、吳心緹\n',
                    '🔵藍隊陣容：林敬倫、潘君侖、顏佑庭、彭小刀、鼓鼓 呂思緯、小春、采子、小8 趙逸嵐、洗菜、李佳薇\n',
                    '\n',
                    '🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆\n',
                    '不搞笑！不做效果！全程玩真的！\n',
                    '全明星運動會，正式開戰！\n',
                    '每週二，中午12點，上架完整版！\n',
                    '\n',
                    '⚠️還沒訂閱嗎？傳送門在這👉https://rb.gy/7uxlh5\n',
                    '👉全明星運動會FaceBook：https://rb.gy/c26gcu\n',
                    '👉全明星運動會Instagram：https://rb.gy/u82tvj\n',
                    '成為這個頻道的會員並獲得獎勵：\n',
                    '👉https://rb.gy/7uxlh5'],
    id: 'dRhYKUIqkkk',
    img_thumbnail: 'https://i.ytimg.com/vi/dRhYKUIqkkk/hqdefault.jpg',
    labels: ['全明星運動會', '胡宇威', '李玖哲', '柯有倫', '姚元浩', '陳漢典', '運動實境節目', '台視', '三立'],
    link: 'https://www.youtube.com/watch?v=dRhYKUIqkkk',
    thumbnail: 'https://i.ytimg.com/vi/dRhYKUIqkkk/maxresdefault.jpg',
    title: '超精彩羽球女子雙打！小8李佳薇合力贏球喜極而泣！｜【全明星運動會】',
    upload_date: '20210421',
    view_count: 9916},
    {channel: '全明星運動會',
     channel_id: 'UCXxAXdFh-cuYXU289kd-pNQ',
     channel_avatar: 'https://yt3.ggpht.com/ytc/AAUvwng9GJZCxSOlAONujyyQj_jZs_PqW0lKIrPnG1sH=s48-c-k-c0x00ffffff-no-rj',
     description: ['#全明星運動會 #第二季 #頻道會員募集中\n',
                    '加入頻道會員👉 https://rb.gy/tzx4nk\n',
                    '主播：徐展元、蔡尚樺\n',
                    '🔴紅隊領隊：江宏傑          🔵藍隊領隊：錢薇娟\n',
                    '🔴紅隊經理：粿粿              🔵藍隊經理：孟潔\n',
                    '🔴紅隊助理教練：喬巴      🔵藍隊助理教練：Choco\n',
                    '🔴紅隊陣容：曹佑寧、王家梁、何孟遠、周予天、小杰 廖允杰、范逸臣、晏柔中、房子 房思瑜、席惟倫、吳心緹\n',
                    '🔵藍隊陣容：林敬倫、潘君侖、顏佑庭、彭小刀、鼓鼓 呂思緯、小春、采子、小8 趙逸嵐、洗菜、李佳薇\n',
                    '\n',
                    '🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆\n',
                    '不搞笑！不做效果！全程玩真的！\n',
                    '全明星運動會，正式開戰！\n',
                    '每週二，中午12點，上架完整版！\n',
                    '\n',
                    '⚠️還沒訂閱嗎？傳送門在這👉https://rb.gy/7uxlh5\n',
                    '👉全明星運動會FaceBook：https://rb.gy/c26gcu\n',
                    '👉全明星運動會Instagram：https://rb.gy/u82tvj'],
    id: '56XXkT4SQnA',
    img_thumbnail: 'https://i.ytimg.com/vi/56XXkT4SQnA/hqdefault.jpg',
    labels: ['全明星運動會', '胡宇威', '李玖哲', '柯有倫', '姚元浩', '陳漢典', '運動實境節目', '台視', '三立'],
    link: 'https://www.youtube.com/watch?v=56XXkT4SQnA',
    thumbnail: 'https://i.ytimg.com/vi_webp/56XXkT4SQnA/maxresdefault.webp',
    title: '背負HBL甲組隊長的壓力！再加上錢姊的戰略！每一球都是關鍵啊！｜【全明星運動會】',
    upload_date: '20210415',
    view_count: 71772},
    {channel: '全明星運動會',
     channel_id: 'UCXxAXdFh-cuYXU289kd-pNQ',
     channel_avatar: 'https://yt3.ggpht.com/ytc/AAUvwng9GJZCxSOlAONujyyQj_jZs_PqW0lKIrPnG1sH=s48-c-k-c0x00ffffff-no-rj',
     description: ['#全明星運動會 #第二季 #頻道會員募集中\n',
                    '加入頻道會員👉 https://rb.gy/tzx4nk\n',
                    '主播：徐展元、蔡尚樺\n',
                    '🔴紅隊領隊：江宏傑          🔵藍隊領隊：錢薇娟\n',
                    '🔴紅隊經理：粿粿              🔵藍隊經理：孟潔\n',
                    '🔴紅隊助理教練：喬巴      🔵藍隊助理教練：Choco\n',
                    '🔴紅隊陣容：曹佑寧、王家梁、何孟遠、周予天、小杰 廖允杰、范逸臣、晏柔中、房子 房思瑜、席惟倫、吳心緹\n',
                    '🔵藍隊陣容：林敬倫、潘君侖、顏佑庭、彭小刀、鼓鼓 呂思緯、小春、采子、小8 趙逸嵐、洗菜、李佳薇\n',
                    '\n',
                    '🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆\n',
                    '不搞笑！不做效果！全程玩真的！\n',
                    '全明星運動會，正式開戰！\n',
                    '每週二，中午12點，上架完整版！\n',
                    '\n',
                    '⚠️還沒訂閱嗎？傳送門在這👉https://rb.gy/7uxlh5\n',
                    '👉全明星運動會FaceBook：https://rb.gy/c26gcu\n',
                    '👉全明星運動會Instagram：https://rb.gy/u82tvj'],
    id: 'ZSnaAa2F_qU',
    img_thumbnail: 'https://i.ytimg.com/vi/ZSnaAa2F_qU/hqdefault.jpg',
    labels: ['全明星運動會', '胡宇威', '李玖哲', '柯有倫', '姚元浩', '陳漢典', '運動實境節目', '台視', '三立'],
    link: 'https://www.youtube.com/watch?v=ZSnaAa2F_qU',
    thumbnail: 'https://i.ytimg.com/vi/ZSnaAa2F_qU/maxresdefault.jpg',
    title: '神力女空氣手槍神！洗菜這一次真的帥爆啦！采子遭錢姊放話：這數字我不喜歡！勢要打出吉利數字！｜【全明星運動會】',
    upload_date: '20210413',
    view_count: 123578},
    {channel: '全明星運動會',
     channel_id: 'UCXxAXdFh-cuYXU289kd-pNQ',
     channel_avatar: 'https://yt3.ggpht.com/ytc/AAUvwng9GJZCxSOlAONujyyQj_jZs_PqW0lKIrPnG1sH=s48-c-k-c0x00ffffff-no-rj',
     description: ['#全明星運動會 #林敬倫 #周予天\n',
                    '主播：徐展元、蔡尚樺\n',
                    '🔴紅隊領隊：江宏傑          🔵藍隊領隊：錢薇娟\n',
                    '🔴紅隊經理：粿粿              🔵藍隊經理：孟潔\n',
                    '🔴紅隊助理教練：喬巴      🔵藍隊助理教練：Choco\n',
                    '🔴紅隊陣容：曹佑寧、王家梁、何孟遠、周予天、小杰 廖允杰、范逸臣、晏柔中、房子 房思瑜、席惟倫、吳心緹\n',
                    '🔵藍隊陣容：林敬倫、潘君侖、顏佑庭、彭小刀、鼓鼓 呂思緯、小春、采子、小8 趙逸嵐、洗菜、李佳薇\n',
                    '\n',
                    '🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆🏆\n',
                    '不搞笑！不做效果！全程玩真的！\n',
                    '全明星運動會，正式開戰！\n',
                    '每週二，中午12點，上架完整版！\n',
                    '\n',
                    '⚠️還沒訂閱嗎？傳送門在這👉https://rb.gy/7uxlh5\n',
                    '👉全明星運動會FaceBook：https://rb.gy/c26gcu\n',
                    '👉全明星運動會Instagram：https://rb.gy/u82tvj'],
    id: 'V4EnK0zZurM',
    img_thumbnail: 'https://i.ytimg.com/vi/V4EnK0zZurM/hqdefault.jpg',
    labels: ['全明星運動會', '胡宇威', '李玖哲', '柯有倫', '姚元浩', '陳漢典', '運動實境節目', '台視', '三立'],
    link: 'https://www.youtube.com/watch?v=V4EnK0zZurM',
    thumbnail: 'https://i.ytimg.com/vi/V4EnK0zZurM/maxresdefault.jpg',
    title: '游泳接力超級大逆轉！？落後超過12公尺～最驚奇的一役！！｜【全明星運動會】',
    upload_date: '20210331',
    view_count: 92392
    }
];

export default VIDEO_DATA;